# Site settings
title: AzStuff
# Privacy - The simple guide 
tag_text: AzStuff
description: A responsive single-page website for Azure Stuff
url: "https://jcabeza.github.io/AzStuff"
baseurl: "/"

font-awesome-include: true # make this false if you don't need font-awesome

# Build settings
markdown: kramdown

exclude: ["README.md"]
